export const dummyProfiles = [
  {
    fullName: "Sarah Chen",
    email: "sarah.chen@email.com",
    location: "San Francisco, CA / PST",
    linkedinUrl: "https://linkedin.com/in/sarahchen",
    profilePicture: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
    type: "Founder",
    lookingFor: "Seeking a technical co-founder with full-stack experience to help scale our AI-powered healthcare platform.",
    bio: "Former Google PM with 8 years in healthcare tech. Built and sold a telemedicine startup. Passionate about democratizing healthcare access through AI.",
    industry: ["Healthcare", "AI/ML", "Technology"],
    skills: ["Product Management", "Business Development", "AI/ML"],
    availability: "Full-time",
    startupStage: "MVP",
    startupName: "HealthAI",
    website: "https://healthai.com",
    status: "approved",
    featured: true
  },
  {
    fullName: "Marcus Rodriguez",
    email: "marcus.r@email.com",
    location: "Austin, TX / CST",
    linkedinUrl: "https://linkedin.com/in/marcusrodriguez",
    profilePicture: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    type: "Co-founder",
    lookingFor: "Looking for a business-minded co-founder to help commercialize our fintech solution for small businesses.",
    bio: "Senior Software Engineer at Stripe. 10+ years building scalable payment systems. Ready to launch my own fintech startup focused on SMB lending.",
    industry: ["Finance", "Technology"],
    skills: ["Engineering", "DevOps", "Finance"],
    availability: "Full-time",
    startupStage: "Idea",
    status: "approved",
    featured: true
  },
  {
    fullName: "Emily Watson",
    email: "emily.watson@email.com",
    location: "London, UK / GMT",
    linkedinUrl: "https://linkedin.com/in/emilywatson",
    profilePicture: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    type: "Founder",
    lookingFor: "Seeking a technical co-founder to build the next generation of sustainable fashion e-commerce platform.",
    bio: "Former Head of Sustainability at H&M. MBA from INSEAD. Building a circular fashion marketplace that connects conscious consumers with sustainable brands.",
    industry: ["E-commerce", "Fashion", "Sustainability"],
    skills: ["Marketing", "Business Development", "Operations"],
    availability: "Full-time",
    startupStage: "Growth",
    startupName: "CircularStyle",
    website: "https://circularstyle.com",
    status: "approved",
    featured: true
  },
  {
    fullName: "David Kim",
    email: "david.kim@email.com",
    location: "Seoul, South Korea / KST",
    linkedinUrl: "https://linkedin.com/in/davidkim",
    profilePicture: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    type: "Co-founder",
    lookingFor: "Looking for a co-founder with gaming industry experience to build the next big mobile gaming platform.",
    bio: "Former Lead Developer at Nexon. Shipped 5+ mobile games with 10M+ downloads. Expertise in Unity, multiplayer systems, and game monetization.",
    industry: ["Gaming", "Entertainment", "Mobile"],
    skills: ["Mobile Development", "Game Development", "UI/UX"],
    availability: "Full-time",
    startupStage: "MVP",
    status: "approved",
    featured: false
  },
  {
    fullName: "Priya Patel",
    email: "priya.patel@email.com",
    location: "Mumbai, India / IST",
    linkedinUrl: "https://linkedin.com/in/priyapatel",
    profilePicture: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    type: "Founder",
    lookingFor: "Seeking a technical co-founder to revolutionize education in emerging markets through AI-powered personalized learning.",
    bio: "Former McKinsey consultant specializing in education sector. Founded 2 EdTech startups in India. Passionate about making quality education accessible to all.",
    industry: ["Education", "AI/ML", "Technology"],
    skills: ["Business Development", "Strategy", "Operations"],
    availability: "Full-time",
    startupStage: "Scaling",
    startupName: "LearnAI",
    website: "https://learnai.in",
    status: "approved",
    featured: false
  },
  {
    fullName: "Alex Thompson",
    email: "alex.thompson@email.com",
    location: "Toronto, Canada / EST",
    linkedinUrl: "https://linkedin.com/in/alexthompson",
    profilePicture: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    type: "Co-founder",
    lookingFor: "Looking for a business co-founder to help scale our blockchain-based supply chain solution for the food industry.",
    bio: "Blockchain architect with 6 years at IBM. Built enterprise blockchain solutions for Fortune 500 companies. Ready to disrupt food traceability.",
    industry: ["Blockchain", "Food & Beverage", "Technology"],
    skills: ["Engineering", "Blockchain", "DevOps"],
    availability: "Part-time",
    startupStage: "MVP",
    status: "approved",
    featured: false
  },
  {
    fullName: "Lisa Zhang",
    email: "lisa.zhang@email.com",
    location: "Singapore / SGT",
    linkedinUrl: "https://linkedin.com/in/lisazhang",
    profilePicture: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
    type: "Founder",
    lookingFor: "Seeking a technical co-founder to build an AI-powered real estate investment platform for retail investors.",
    bio: "Former VP at Goldman Sachs Real Estate. 12 years in real estate finance. Building tools to democratize real estate investing through technology.",
    industry: ["Real Estate", "Finance", "AI/ML"],
    skills: ["Finance", "Business Development", "Strategy"],
    availability: "Full-time",
    startupStage: "Idea",
    status: "approved",
    featured: false
  },
  {
    fullName: "James Wilson",
    email: "james.wilson@email.com",
    location: "Sydney, Australia / AEST",
    linkedinUrl: "https://linkedin.com/in/jameswilson",
    profilePicture: "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop&crop=face",
    type: "Co-founder",
    lookingFor: "Looking for a business co-founder to help launch our renewable energy marketplace connecting homeowners with solar installers.",
    bio: "Renewable energy engineer with 8 years at Tesla Energy. Led solar installation projects across Australia. Passionate about accelerating clean energy adoption.",
    industry: ["Energy", "Sustainability", "Technology"],
    skills: ["Engineering", "Operations", "Project Management"],
    availability: "Full-time",
    startupStage: "Growth",
    startupName: "SolarConnect",
    status: "approved",
    featured: false
  },
  {
    fullName: "Maria Gonzalez",
    email: "maria.gonzalez@email.com",
    location: "Mexico City, Mexico / CST",
    linkedinUrl: "https://linkedin.com/in/mariagonzalez",
    profilePicture: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=150&h=150&fit=crop&crop=face",
    type: "Founder",
    lookingFor: "Seeking a technical co-founder to build a logistics platform connecting small farmers with urban markets in Latin America.",
    bio: "Former Head of Operations at Uber Eats LATAM. MBA from Wharton. Passionate about solving food distribution challenges in emerging markets.",
    industry: ["Logistics", "Food & Beverage", "Technology"],
    skills: ["Operations", "Business Development", "Strategy"],
    availability: "Full-time",
    startupStage: "MVP",
    startupName: "FarmConnect",
    status: "approved",
    featured: false
  },
  {
    fullName: "Robert Chen",
    email: "robert.chen@email.com",
    location: "Vancouver, Canada / PST",
    linkedinUrl: "https://linkedin.com/in/robertchen",
    profilePicture: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
    type: "Co-founder",
    lookingFor: "Looking for a business co-founder to help commercialize our IoT solution for smart city infrastructure.",
    bio: "IoT systems architect with 10 years at Cisco. Built connected infrastructure for 20+ cities. Ready to launch smart city solutions for mid-size municipalities.",
    industry: ["IoT", "Technology", "Smart Cities"],
    skills: ["Engineering", "IoT", "Systems Architecture"],
    availability: "Full-time",
    startupStage: "Idea",
    status: "approved",
    featured: false
  },
  {
    fullName: "Nina Petrov",
    email: "nina.petrov@email.com",
    location: "Berlin, Germany / CET",
    linkedinUrl: "https://linkedin.com/in/ninapetrov",
    profilePicture: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
    type: "Founder",
    lookingFor: "Seeking a technical co-founder to build a mental health platform using VR therapy for anxiety and depression treatment.",
    bio: "Clinical psychologist with 8 years experience. PhD in VR therapy applications. Building evidence-based mental health solutions using immersive technology.",
    industry: ["Healthcare", "Mental Health", "VR/AR"],
    skills: ["Healthcare", "Research", "Product Management"],
    availability: "Full-time",
    startupStage: "MVP",
    startupName: "MindVR",
    status: "approved",
    featured: false
  },
  {
    fullName: "Ahmed Hassan",
    email: "ahmed.hassan@email.com",
    location: "Dubai, UAE / GST",
    linkedinUrl: "https://linkedin.com/in/ahmedhassan",
    profilePicture: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    type: "Co-founder",
    lookingFor: "Looking for a business co-founder to scale our cybersecurity solution for small and medium enterprises in MENA region.",
    bio: "Cybersecurity expert with 12 years at Kaspersky. Built security solutions for government and enterprise clients. Focused on making cybersecurity accessible to SMEs.",
    industry: ["Cybersecurity", "Technology", "Enterprise"],
    skills: ["Cybersecurity", "Engineering", "Enterprise Sales"],
    availability: "Full-time",
    startupStage: "Growth",
    startupName: "SecureShield",
    website: "https://secureshield.ae",
    status: "approved",
    featured: false
  }
];